version: '3'

services:
  cloudingapp:
    container_name: cloudingapp
    build:
      context: ./clouding-api/
      dockerfile: Dockerfile
    image: twcammaster.uv.es/proyecto-2-cloudingapp
    deploy:
      replicas: 2
    ports:
      - "8080:8080"
    networks:
      - clouding-network
    depends_on:
      - mysqldb
      - nginx
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=airlinedb1
      - DATABASE_PORT=3306

  cloudingreactive:
    container_name: cloudingreactive
    build:
      context: ./clouding-reactive/
      dockerfile: Dockerfile
    image: twcammaster.uv.es/proyecto-2-cloudingreactive
    deploy:
      replicas: 2
    ports:
      - "8081:8081"
    networks:
      - clouding-network
    depends_on:
      - dbmongo
      - nginx

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - clouding-network
    command: --max_allowed_packet=32505856
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=airlines
      - MYSQL_PASSWORD=root
    restart: always
    depends_on:
      - nginx

  dbmongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - clouding-network
    volumes:
      - mongodata:/data/db
    depends_on:
      - nginx

  nginx:
    build:
      context: ./clouding-script/nginx
      dockerfile: Dockerfile
    image: twcammaster.uv.es/proyecto-2-nginx
    deploy:
      replicas: 2
    ports:
      - "80:80"
    networks:
      - clouding-network
    restart: always

networks:
  clouding-network:
volumes:
  mysqldata:
  mongodata: